https://licensebuttons.net/l/by-sa/4.0/80x15.png [[./LICENSE.md][License: Creative Commons BY-SA-ND 4.0]]
* About This Repository
This repository houses the source documents for the course materials I use in RLG239, "[[http://wildwater.hackinghistory.ca][Wild Waters]]", a special topics class in the [[http://religion.utoronto.ca/][Department for the Study of Religion]] at the University of Toronto.  The class is one of several pilots in a project co-ordinated by Prof. Frances Garrett and me, "[[http://outdoors.hackinghistory.ca/][U of T Outdoors]]", and is supported by an [[http://www.artsci.utoronto.ca/faculty-staff/teacher-info/atlas/index_html][ATLAS Grant]] from the Faculty of Arts and Sciences.  

The documents in this repository have been written in the [[http://orgmode.org/org.html#Introduction][org-mode]] syntax, a textual markup language similar to [[https://en.wikipedia.org/wiki/Markdown][Markdown]] only way better in pretty much every way. They've been written so that they export easily to several formats but especially to the Markdown flavour used by [[https://gohugo.io/][Hugo]], which I use to generate the course website. The site generation process is simple but involves a couple of steps; I hope to document it here soon. The final course structure looks a little different from the structure of this repository, and relies to some extent on sophisticated features of org-mode and the [[https://www.gnu.org/software/emacs/][Emacs]] text editor. As soon as I have everything properly automated and cleaned up, I will post a full set of instructions here.  

To see the site in action, check out its [[http://wildwater.hackinghistory.ca/][rendered home on the web]]!
